version: '3.8'

services:
  ffc-analytics:
    build:
      dockerfile: Dockerfile
    image: nestjs
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - '4001:4001'
    volumes:
      - .:/app
      - /app/node_modules
